// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/koma.dart';
import 'api/metadata.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1840077829;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'metadata_engine',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<KirChapterDto> crateApiKomaChapterKirByIndex({
    required String komaPath,
    required int index,
  });

  Future<ChapterPayloadDto> crateApiKomaChapterPayloadByIndex({
    required String komaPath,
    required int index,
  });

  Future<Uint8List> crateApiKomaCompileEpub({required String path});

  Future<void> crateApiSimpleInitApp();

  Future<LayoutResultDto> crateApiKomaLayoutChapterPages({
    required String komaPath,
    required int index,
    required int width,
    required int height,
    required double fontSize,
    required double lineHeight,
    required double margin,
    required double firstPageInset,
    required String fontPath,
  });

  Future<List<BookMetadataResult>> crateApiMetadataLookupBooks({
    required List<BookLookupQuery> queries,
    String? googleApiKey,
  });

  Future<List<KomaChapterInfo>> crateApiKomaPackageChapters({
    required String komaPath,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<KirChapterDto> crateApiKomaChapterKirByIndex({
    required String komaPath,
    required int index,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(komaPath, serializer);
          sse_encode_u_32(index, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_kir_chapter_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKomaChapterKirByIndexConstMeta,
        argValues: [komaPath, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomaChapterKirByIndexConstMeta =>
      const TaskConstMeta(
        debugName: "chapter_kir_by_index",
        argNames: ["komaPath", "index"],
      );

  @override
  Future<ChapterPayloadDto> crateApiKomaChapterPayloadByIndex({
    required String komaPath,
    required int index,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(komaPath, serializer);
          sse_encode_u_32(index, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chapter_payload_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKomaChapterPayloadByIndexConstMeta,
        argValues: [komaPath, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomaChapterPayloadByIndexConstMeta =>
      const TaskConstMeta(
        debugName: "chapter_payload_by_index",
        argNames: ["komaPath", "index"],
      );

  @override
  Future<Uint8List> crateApiKomaCompileEpub({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKomaCompileEpubConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomaCompileEpubConstMeta =>
      const TaskConstMeta(debugName: "compile_epub", argNames: ["path"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<LayoutResultDto> crateApiKomaLayoutChapterPages({
    required String komaPath,
    required int index,
    required int width,
    required int height,
    required double fontSize,
    required double lineHeight,
    required double margin,
    required double firstPageInset,
    required String fontPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(komaPath, serializer);
          sse_encode_u_32(index, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_f_64(fontSize, serializer);
          sse_encode_f_64(lineHeight, serializer);
          sse_encode_f_64(margin, serializer);
          sse_encode_f_64(firstPageInset, serializer);
          sse_encode_String(fontPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_layout_result_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKomaLayoutChapterPagesConstMeta,
        argValues: [
          komaPath,
          index,
          width,
          height,
          fontSize,
          lineHeight,
          margin,
          firstPageInset,
          fontPath,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomaLayoutChapterPagesConstMeta =>
      const TaskConstMeta(
        debugName: "layout_chapter_pages",
        argNames: [
          "komaPath",
          "index",
          "width",
          "height",
          "fontSize",
          "lineHeight",
          "margin",
          "firstPageInset",
          "fontPath",
        ],
      );

  @override
  Future<List<BookMetadataResult>> crateApiMetadataLookupBooks({
    required List<BookLookupQuery> queries,
    String? googleApiKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_book_lookup_query(queries, serializer);
          sse_encode_opt_String(googleApiKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_book_metadata_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMetadataLookupBooksConstMeta,
        argValues: [queries, googleApiKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMetadataLookupBooksConstMeta =>
      const TaskConstMeta(
        debugName: "lookup_books",
        argNames: ["queries", "googleApiKey"],
      );

  @override
  Future<List<KomaChapterInfo>> crateApiKomaPackageChapters({
    required String komaPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(komaPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_koma_chapter_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKomaPackageChaptersConstMeta,
        argValues: [komaPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomaPackageChaptersConstMeta =>
      const TaskConstMeta(
        debugName: "package_chapters",
        argNames: ["komaPath"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BookLookupQuery dco_decode_book_lookup_query(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BookLookupQuery(
      id: dco_decode_i_64(arr[0]),
      title: dco_decode_String(arr[1]),
      author: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  BookMetadataResult dco_decode_book_metadata_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return BookMetadataResult(
      id: dco_decode_i_64(arr[0]),
      title: dco_decode_String(arr[1]),
      author: dco_decode_opt_String(arr[2]),
      coverUrl: dco_decode_opt_String(arr[3]),
      genres: dco_decode_list_String(arr[4]),
      releaseDate: dco_decode_opt_String(arr[5]),
      source: dco_decode_String(arr[6]),
      remoteId: dco_decode_opt_String(arr[7]),
      found: dco_decode_bool(arr[8]),
      error: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SceneChromeDto dco_decode_box_autoadd_scene_chrome_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_scene_chrome_dto(raw);
  }

  @protected
  ChapterPayloadDto dco_decode_chapter_payload_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ChapterPayloadDto(
      chapter: dco_decode_kir_chapter_dto(arr[0]),
      scene: dco_decode_opt_box_autoadd_scene_chrome_dto(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  KirBlockDto dco_decode_kir_block_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return KirBlockDto(
      kind: dco_decode_String(arr[0]),
      spans: dco_decode_list_kir_span_dto(arr[1]),
      mediaId: dco_decode_opt_String(arr[2]),
      alt: dco_decode_opt_String(arr[3]),
      ordered: dco_decode_bool(arr[4]),
      children: dco_decode_list_kir_block_dto(arr[5]),
    );
  }

  @protected
  KirChapterDto dco_decode_kir_chapter_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return KirChapterDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_opt_String(arr[1]),
      blocks: dco_decode_list_kir_block_dto(arr[2]),
    );
  }

  @protected
  KirSpanDto dco_decode_kir_span_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return KirSpanDto(
      text: dco_decode_String(arr[0]),
      bold: dco_decode_bool(arr[1]),
      italic: dco_decode_bool(arr[2]),
      underline: dco_decode_bool(arr[3]),
      color: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  KomaChapterInfo dco_decode_koma_chapter_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KomaChapterInfo(
      id: dco_decode_String(arr[0]),
      title: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  LayoutGlyphDto dco_decode_layout_glyph_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return LayoutGlyphDto(
      x: dco_decode_f_64(arr[0]),
      y: dco_decode_f_64(arr[1]),
      width: dco_decode_f_64(arr[2]),
      height: dco_decode_f_64(arr[3]),
      charStart: dco_decode_u_32(arr[4]),
      charEnd: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  LayoutLineDto dco_decode_layout_line_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LayoutLineDto(
      y: dco_decode_f_64(arr[0]),
      height: dco_decode_f_64(arr[1]),
      charStart: dco_decode_u_32(arr[2]),
      charEnd: dco_decode_u_32(arr[3]),
      glyphs: dco_decode_list_layout_glyph_dto(arr[4]),
    );
  }

  @protected
  LayoutPageDto dco_decode_layout_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LayoutPageDto(
      charStart: dco_decode_u_32(arr[0]),
      charEnd: dco_decode_u_32(arr[1]),
      lines: dco_decode_list_layout_line_dto(arr[2]),
    );
  }

  @protected
  LayoutResultDto dco_decode_layout_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LayoutResultDto(
      plainText: dco_decode_String(arr[0]),
      pages: dco_decode_list_layout_page_dto(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BookLookupQuery> dco_decode_list_book_lookup_query(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_book_lookup_query).toList();
  }

  @protected
  List<BookMetadataResult> dco_decode_list_book_metadata_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_book_metadata_result).toList();
  }

  @protected
  List<KirBlockDto> dco_decode_list_kir_block_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_kir_block_dto).toList();
  }

  @protected
  List<KirSpanDto> dco_decode_list_kir_span_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_kir_span_dto).toList();
  }

  @protected
  List<KomaChapterInfo> dco_decode_list_koma_chapter_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_koma_chapter_info).toList();
  }

  @protected
  List<LayoutGlyphDto> dco_decode_list_layout_glyph_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_layout_glyph_dto).toList();
  }

  @protected
  List<LayoutLineDto> dco_decode_list_layout_line_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_layout_line_dto).toList();
  }

  @protected
  List<LayoutPageDto> dco_decode_list_layout_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_layout_page_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SceneChromeDto? dco_decode_opt_box_autoadd_scene_chrome_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_scene_chrome_dto(raw);
  }

  @protected
  SceneChromeDto dco_decode_scene_chrome_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SceneChromeDto(
      environmentKind: dco_decode_String(arr[0]),
      backgroundHex: dco_decode_String(arr[1]),
      ambientHex: dco_decode_String(arr[2]),
      ambientIntensity: dco_decode_f_64(arr[3]),
      frost: dco_decode_f_64(arr[4]),
      fadeSeconds: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BookLookupQuery sse_decode_book_lookup_query(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    return BookLookupQuery(id: var_id, title: var_title, author: var_author);
  }

  @protected
  BookMetadataResult sse_decode_book_metadata_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    var var_genres = sse_decode_list_String(deserializer);
    var var_releaseDate = sse_decode_opt_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_remoteId = sse_decode_opt_String(deserializer);
    var var_found = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return BookMetadataResult(
      id: var_id,
      title: var_title,
      author: var_author,
      coverUrl: var_coverUrl,
      genres: var_genres,
      releaseDate: var_releaseDate,
      source: var_source,
      remoteId: var_remoteId,
      found: var_found,
      error: var_error,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SceneChromeDto sse_decode_box_autoadd_scene_chrome_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_scene_chrome_dto(deserializer));
  }

  @protected
  ChapterPayloadDto sse_decode_chapter_payload_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapter = sse_decode_kir_chapter_dto(deserializer);
    var var_scene = sse_decode_opt_box_autoadd_scene_chrome_dto(deserializer);
    return ChapterPayloadDto(chapter: var_chapter, scene: var_scene);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  KirBlockDto sse_decode_kir_block_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_spans = sse_decode_list_kir_span_dto(deserializer);
    var var_mediaId = sse_decode_opt_String(deserializer);
    var var_alt = sse_decode_opt_String(deserializer);
    var var_ordered = sse_decode_bool(deserializer);
    var var_children = sse_decode_list_kir_block_dto(deserializer);
    return KirBlockDto(
      kind: var_kind,
      spans: var_spans,
      mediaId: var_mediaId,
      alt: var_alt,
      ordered: var_ordered,
      children: var_children,
    );
  }

  @protected
  KirChapterDto sse_decode_kir_chapter_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_blocks = sse_decode_list_kir_block_dto(deserializer);
    return KirChapterDto(id: var_id, title: var_title, blocks: var_blocks);
  }

  @protected
  KirSpanDto sse_decode_kir_span_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_bold = sse_decode_bool(deserializer);
    var var_italic = sse_decode_bool(deserializer);
    var var_underline = sse_decode_bool(deserializer);
    var var_color = sse_decode_opt_String(deserializer);
    return KirSpanDto(
      text: var_text,
      bold: var_bold,
      italic: var_italic,
      underline: var_underline,
      color: var_color,
    );
  }

  @protected
  KomaChapterInfo sse_decode_koma_chapter_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    return KomaChapterInfo(id: var_id, title: var_title);
  }

  @protected
  LayoutGlyphDto sse_decode_layout_glyph_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    var var_width = sse_decode_f_64(deserializer);
    var var_height = sse_decode_f_64(deserializer);
    var var_charStart = sse_decode_u_32(deserializer);
    var var_charEnd = sse_decode_u_32(deserializer);
    return LayoutGlyphDto(
      x: var_x,
      y: var_y,
      width: var_width,
      height: var_height,
      charStart: var_charStart,
      charEnd: var_charEnd,
    );
  }

  @protected
  LayoutLineDto sse_decode_layout_line_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_y = sse_decode_f_64(deserializer);
    var var_height = sse_decode_f_64(deserializer);
    var var_charStart = sse_decode_u_32(deserializer);
    var var_charEnd = sse_decode_u_32(deserializer);
    var var_glyphs = sse_decode_list_layout_glyph_dto(deserializer);
    return LayoutLineDto(
      y: var_y,
      height: var_height,
      charStart: var_charStart,
      charEnd: var_charEnd,
      glyphs: var_glyphs,
    );
  }

  @protected
  LayoutPageDto sse_decode_layout_page_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_charStart = sse_decode_u_32(deserializer);
    var var_charEnd = sse_decode_u_32(deserializer);
    var var_lines = sse_decode_list_layout_line_dto(deserializer);
    return LayoutPageDto(
      charStart: var_charStart,
      charEnd: var_charEnd,
      lines: var_lines,
    );
  }

  @protected
  LayoutResultDto sse_decode_layout_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_plainText = sse_decode_String(deserializer);
    var var_pages = sse_decode_list_layout_page_dto(deserializer);
    return LayoutResultDto(plainText: var_plainText, pages: var_pages);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BookLookupQuery> sse_decode_list_book_lookup_query(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BookLookupQuery>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_book_lookup_query(deserializer));
    }
    return ans_;
  }

  @protected
  List<BookMetadataResult> sse_decode_list_book_metadata_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BookMetadataResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_book_metadata_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<KirBlockDto> sse_decode_list_kir_block_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KirBlockDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_kir_block_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<KirSpanDto> sse_decode_list_kir_span_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KirSpanDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_kir_span_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<KomaChapterInfo> sse_decode_list_koma_chapter_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KomaChapterInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_koma_chapter_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<LayoutGlyphDto> sse_decode_list_layout_glyph_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LayoutGlyphDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_layout_glyph_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<LayoutLineDto> sse_decode_list_layout_line_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LayoutLineDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_layout_line_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<LayoutPageDto> sse_decode_list_layout_page_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LayoutPageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_layout_page_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SceneChromeDto? sse_decode_opt_box_autoadd_scene_chrome_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_scene_chrome_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SceneChromeDto sse_decode_scene_chrome_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_environmentKind = sse_decode_String(deserializer);
    var var_backgroundHex = sse_decode_String(deserializer);
    var var_ambientHex = sse_decode_String(deserializer);
    var var_ambientIntensity = sse_decode_f_64(deserializer);
    var var_frost = sse_decode_f_64(deserializer);
    var var_fadeSeconds = sse_decode_f_64(deserializer);
    return SceneChromeDto(
      environmentKind: var_environmentKind,
      backgroundHex: var_backgroundHex,
      ambientHex: var_ambientHex,
      ambientIntensity: var_ambientIntensity,
      frost: var_frost,
      fadeSeconds: var_fadeSeconds,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_book_lookup_query(
    BookLookupQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.author, serializer);
  }

  @protected
  void sse_encode_book_metadata_result(
    BookMetadataResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
    sse_encode_list_String(self.genres, serializer);
    sse_encode_opt_String(self.releaseDate, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_opt_String(self.remoteId, serializer);
    sse_encode_bool(self.found, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_scene_chrome_dto(
    SceneChromeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scene_chrome_dto(self, serializer);
  }

  @protected
  void sse_encode_chapter_payload_dto(
    ChapterPayloadDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_kir_chapter_dto(self.chapter, serializer);
    sse_encode_opt_box_autoadd_scene_chrome_dto(self.scene, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_kir_block_dto(KirBlockDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_list_kir_span_dto(self.spans, serializer);
    sse_encode_opt_String(self.mediaId, serializer);
    sse_encode_opt_String(self.alt, serializer);
    sse_encode_bool(self.ordered, serializer);
    sse_encode_list_kir_block_dto(self.children, serializer);
  }

  @protected
  void sse_encode_kir_chapter_dto(
    KirChapterDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_list_kir_block_dto(self.blocks, serializer);
  }

  @protected
  void sse_encode_kir_span_dto(KirSpanDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_bool(self.bold, serializer);
    sse_encode_bool(self.italic, serializer);
    sse_encode_bool(self.underline, serializer);
    sse_encode_opt_String(self.color, serializer);
  }

  @protected
  void sse_encode_koma_chapter_info(
    KomaChapterInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.title, serializer);
  }

  @protected
  void sse_encode_layout_glyph_dto(
    LayoutGlyphDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
    sse_encode_f_64(self.width, serializer);
    sse_encode_f_64(self.height, serializer);
    sse_encode_u_32(self.charStart, serializer);
    sse_encode_u_32(self.charEnd, serializer);
  }

  @protected
  void sse_encode_layout_line_dto(
    LayoutLineDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.y, serializer);
    sse_encode_f_64(self.height, serializer);
    sse_encode_u_32(self.charStart, serializer);
    sse_encode_u_32(self.charEnd, serializer);
    sse_encode_list_layout_glyph_dto(self.glyphs, serializer);
  }

  @protected
  void sse_encode_layout_page_dto(
    LayoutPageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.charStart, serializer);
    sse_encode_u_32(self.charEnd, serializer);
    sse_encode_list_layout_line_dto(self.lines, serializer);
  }

  @protected
  void sse_encode_layout_result_dto(
    LayoutResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.plainText, serializer);
    sse_encode_list_layout_page_dto(self.pages, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_book_lookup_query(
    List<BookLookupQuery> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_book_lookup_query(item, serializer);
    }
  }

  @protected
  void sse_encode_list_book_metadata_result(
    List<BookMetadataResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_book_metadata_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_kir_block_dto(
    List<KirBlockDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_kir_block_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_kir_span_dto(
    List<KirSpanDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_kir_span_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_koma_chapter_info(
    List<KomaChapterInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_koma_chapter_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_layout_glyph_dto(
    List<LayoutGlyphDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_layout_glyph_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_layout_line_dto(
    List<LayoutLineDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_layout_line_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_layout_page_dto(
    List<LayoutPageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_layout_page_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_scene_chrome_dto(
    SceneChromeDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_scene_chrome_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_scene_chrome_dto(
    SceneChromeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.environmentKind, serializer);
    sse_encode_String(self.backgroundHex, serializer);
    sse_encode_String(self.ambientHex, serializer);
    sse_encode_f_64(self.ambientIntensity, serializer);
    sse_encode_f_64(self.frost, serializer);
    sse_encode_f_64(self.fadeSeconds, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
