// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/koma.dart';
import 'api/metadata.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BookLookupQuery dco_decode_book_lookup_query(dynamic raw);

  @protected
  BookMetadataResult dco_decode_book_metadata_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KirBlockDto dco_decode_kir_block_dto(dynamic raw);

  @protected
  KirChapterDto dco_decode_kir_chapter_dto(dynamic raw);

  @protected
  KirSpanDto dco_decode_kir_span_dto(dynamic raw);

  @protected
  KomaChapterInfo dco_decode_koma_chapter_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BookLookupQuery> dco_decode_list_book_lookup_query(dynamic raw);

  @protected
  List<BookMetadataResult> dco_decode_list_book_metadata_result(dynamic raw);

  @protected
  List<KirBlockDto> dco_decode_list_kir_block_dto(dynamic raw);

  @protected
  List<KirSpanDto> dco_decode_list_kir_span_dto(dynamic raw);

  @protected
  List<KomaChapterInfo> dco_decode_list_koma_chapter_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BookLookupQuery sse_decode_book_lookup_query(SseDeserializer deserializer);

  @protected
  BookMetadataResult sse_decode_book_metadata_result(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KirBlockDto sse_decode_kir_block_dto(SseDeserializer deserializer);

  @protected
  KirChapterDto sse_decode_kir_chapter_dto(SseDeserializer deserializer);

  @protected
  KirSpanDto sse_decode_kir_span_dto(SseDeserializer deserializer);

  @protected
  KomaChapterInfo sse_decode_koma_chapter_info(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BookLookupQuery> sse_decode_list_book_lookup_query(
    SseDeserializer deserializer,
  );

  @protected
  List<BookMetadataResult> sse_decode_list_book_metadata_result(
    SseDeserializer deserializer,
  );

  @protected
  List<KirBlockDto> sse_decode_list_kir_block_dto(SseDeserializer deserializer);

  @protected
  List<KirSpanDto> sse_decode_list_kir_span_dto(SseDeserializer deserializer);

  @protected
  List<KomaChapterInfo> sse_decode_list_koma_chapter_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_book_lookup_query(
    BookLookupQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_book_metadata_result(
    BookMetadataResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_kir_block_dto(KirBlockDto self, SseSerializer serializer);

  @protected
  void sse_encode_kir_chapter_dto(KirChapterDto self, SseSerializer serializer);

  @protected
  void sse_encode_kir_span_dto(KirSpanDto self, SseSerializer serializer);

  @protected
  void sse_encode_koma_chapter_info(
    KomaChapterInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_book_lookup_query(
    List<BookLookupQuery> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_book_metadata_result(
    List<BookMetadataResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_kir_block_dto(
    List<KirBlockDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_kir_span_dto(
    List<KirSpanDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_koma_chapter_info(
    List<KomaChapterInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
