// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `block_to_dto`, `chapter_to_dto`, `layout_result_to_dto`, `scene_to_chrome`, `spans_to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Compile an EPUB file on disk into `.koma` zip bytes (default theme).
Future<Uint8List> compileEpub({required String path}) =>
    RustLib.instance.api.crateApiKomaCompileEpub(path: path);

/// Chapter ids/titles from a `.koma` file (manifest only).
Future<List<KomaChapterInfo>> packageChapters({required String komaPath}) =>
    RustLib.instance.api.crateApiKomaPackageChapters(komaPath: komaPath);

/// Decode one chapter by spine index from a `.koma` file.
Future<KirChapterDto> chapterKirByIndex({
  required String komaPath,
  required int index,
}) => RustLib.instance.api.crateApiKomaChapterKirByIndex(
  komaPath: komaPath,
  index: index,
);

/// KIR plus scene chrome in one zip open.
Future<ChapterPayloadDto> chapterPayloadByIndex({
  required String komaPath,
  required int index,
}) => RustLib.instance.api.crateApiKomaChapterPayloadByIndex(
  komaPath: komaPath,
  index: index,
);

/// Layout one chapter into page-sized glyph boxes (Level 3).
///
/// Offsets are Dart `String` indices (UTF-16) into the returned `plain_text`,
/// matching `KirToDocument` (no chapter title, images 0 chars). `line_height`
/// is in pixels (font size times the reader's line-height multiplier).
/// `first_page_inset` is reserved on page 0 for the chapter title.
/// `font_path` is the TTF/OTF the reader paints with (empty = platform faces).
Future<LayoutResultDto> layoutChapterPages({
  required String komaPath,
  required int index,
  required int width,
  required int height,
  required double fontSize,
  required double lineHeight,
  required double margin,
  required double firstPageInset,
  required String fontPath,
}) => RustLib.instance.api.crateApiKomaLayoutChapterPages(
  komaPath: komaPath,
  index: index,
  width: width,
  height: height,
  fontSize: fontSize,
  lineHeight: lineHeight,
  margin: margin,
  firstPageInset: firstPageInset,
  fontPath: fontPath,
);

class ChapterPayloadDto {
  final KirChapterDto chapter;
  final SceneChromeDto? scene;

  const ChapterPayloadDto({required this.chapter, this.scene});

  @override
  int get hashCode => chapter.hashCode ^ scene.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterPayloadDto &&
          runtimeType == other.runtimeType &&
          chapter == other.chapter &&
          scene == other.scene;
}

/// One KIR block, with quote/list children nested (Dart flattens).
class KirBlockDto {
  /// `paragraph`, `heading1`…`heading6`, `image`, `media`, `quote`, `list`.
  final String kind;
  final List<KirSpanDto> spans;
  final String? mediaId;
  final String? alt;
  final bool ordered;
  final List<KirBlockDto> children;

  const KirBlockDto({
    required this.kind,
    required this.spans,
    this.mediaId,
    this.alt,
    required this.ordered,
    required this.children,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      spans.hashCode ^
      mediaId.hashCode ^
      alt.hashCode ^
      ordered.hashCode ^
      children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KirBlockDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          spans == other.spans &&
          mediaId == other.mediaId &&
          alt == other.alt &&
          ordered == other.ordered &&
          children == other.children;
}

class KirChapterDto {
  final String id;
  final String? title;
  final List<KirBlockDto> blocks;

  const KirChapterDto({required this.id, this.title, required this.blocks});

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ blocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KirChapterDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          blocks == other.blocks;
}

/// Inline run. KIR `SpanStyle` has no href/code; those stay on the HTML path.
class KirSpanDto {
  final String text;
  final bool bold;
  final bool italic;
  final bool underline;
  final String? color;

  const KirSpanDto({
    required this.text,
    required this.bold,
    required this.italic,
    required this.underline,
    this.color,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      bold.hashCode ^
      italic.hashCode ^
      underline.hashCode ^
      color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KirSpanDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          bold == other.bold &&
          italic == other.italic &&
          underline == other.underline &&
          color == other.color;
}

/// Manifest row for one spine chapter.
class KomaChapterInfo {
  final String id;
  final String? title;

  const KomaChapterInfo({required this.id, this.title});

  @override
  int get hashCode => id.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KomaChapterInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title;
}

class LayoutGlyphDto {
  final double x;
  final double y;
  final double width;
  final double height;
  final int charStart;
  final int charEnd;

  const LayoutGlyphDto({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    required this.charStart,
    required this.charEnd,
  });

  @override
  int get hashCode =>
      x.hashCode ^
      y.hashCode ^
      width.hashCode ^
      height.hashCode ^
      charStart.hashCode ^
      charEnd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayoutGlyphDto &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height &&
          charStart == other.charStart &&
          charEnd == other.charEnd;
}

class LayoutLineDto {
  final double y;
  final double height;
  final int charStart;
  final int charEnd;
  final List<LayoutGlyphDto> glyphs;

  const LayoutLineDto({
    required this.y,
    required this.height,
    required this.charStart,
    required this.charEnd,
    required this.glyphs,
  });

  @override
  int get hashCode =>
      y.hashCode ^
      height.hashCode ^
      charStart.hashCode ^
      charEnd.hashCode ^
      glyphs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayoutLineDto &&
          runtimeType == other.runtimeType &&
          y == other.y &&
          height == other.height &&
          charStart == other.charStart &&
          charEnd == other.charEnd &&
          glyphs == other.glyphs;
}

class LayoutPageDto {
  final int charStart;
  final int charEnd;
  final List<LayoutLineDto> lines;

  const LayoutPageDto({
    required this.charStart,
    required this.charEnd,
    required this.lines,
  });

  @override
  int get hashCode => charStart.hashCode ^ charEnd.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayoutPageDto &&
          runtimeType == other.runtimeType &&
          charStart == other.charStart &&
          charEnd == other.charEnd &&
          lines == other.lines;
}

class LayoutResultDto {
  final String plainText;
  final List<LayoutPageDto> pages;

  const LayoutResultDto({required this.plainText, required this.pages});

  @override
  int get hashCode => plainText.hashCode ^ pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayoutResultDto &&
          runtimeType == other.runtimeType &&
          plainText == other.plainText &&
          pages == other.pages;
}

/// Presentation chrome only — not the effect graph or typography.
class SceneChromeDto {
  /// `indoor`, `outdoor`, `space`, or `abstract`.
  final String environmentKind;
  final String backgroundHex;
  final String ambientHex;
  final double ambientIntensity;
  final double frost;
  final double fadeSeconds;

  const SceneChromeDto({
    required this.environmentKind,
    required this.backgroundHex,
    required this.ambientHex,
    required this.ambientIntensity,
    required this.frost,
    required this.fadeSeconds,
  });

  @override
  int get hashCode =>
      environmentKind.hashCode ^
      backgroundHex.hashCode ^
      ambientHex.hashCode ^
      ambientIntensity.hashCode ^
      frost.hashCode ^
      fadeSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SceneChromeDto &&
          runtimeType == other.runtimeType &&
          environmentKind == other.environmentKind &&
          backgroundHex == other.backgroundHex &&
          ambientHex == other.ambientHex &&
          ambientIntensity == other.ambientIntensity &&
          frost == other.frost &&
          fadeSeconds == other.fadeSeconds;
}
