// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `block_to_dto`, `chapter_to_dto`, `spans_to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Compile an EPUB file on disk into `.koma` zip bytes (default theme).
Future<Uint8List> compileEpub({required String path}) =>
    RustLib.instance.api.crateApiKomaCompileEpub(path: path);

/// Chapter ids/titles from a `.koma` file (manifest only).
Future<List<KomaChapterInfo>> packageChapters({required String komaPath}) =>
    RustLib.instance.api.crateApiKomaPackageChapters(komaPath: komaPath);

/// Decode one chapter by spine index from a `.koma` file.
Future<KirChapterDto> chapterKirByIndex({
  required String komaPath,
  required int index,
}) => RustLib.instance.api.crateApiKomaChapterKirByIndex(
  komaPath: komaPath,
  index: index,
);

/// One KIR block, with quote/list children nested (Dart flattens).
class KirBlockDto {
  /// `paragraph`, `heading1`…`heading6`, `image`, `media`, `quote`, `list`.
  final String kind;
  final List<KirSpanDto> spans;
  final String? mediaId;
  final String? alt;
  final bool ordered;
  final List<KirBlockDto> children;

  const KirBlockDto({
    required this.kind,
    required this.spans,
    this.mediaId,
    this.alt,
    required this.ordered,
    required this.children,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      spans.hashCode ^
      mediaId.hashCode ^
      alt.hashCode ^
      ordered.hashCode ^
      children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KirBlockDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          spans == other.spans &&
          mediaId == other.mediaId &&
          alt == other.alt &&
          ordered == other.ordered &&
          children == other.children;
}

class KirChapterDto {
  final String id;
  final String? title;
  final List<KirBlockDto> blocks;

  const KirChapterDto({required this.id, this.title, required this.blocks});

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ blocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KirChapterDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          blocks == other.blocks;
}

/// Inline run. KIR `SpanStyle` has no href/code; those stay on the HTML path.
class KirSpanDto {
  final String text;
  final bool bold;
  final bool italic;
  final bool underline;
  final String? color;

  const KirSpanDto({
    required this.text,
    required this.bold,
    required this.italic,
    required this.underline,
    this.color,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      bold.hashCode ^
      italic.hashCode ^
      underline.hashCode ^
      color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KirSpanDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          bold == other.bold &&
          italic == other.italic &&
          underline == other.underline &&
          color == other.color;
}

/// Manifest row for one spine chapter.
class KomaChapterInfo {
  final String id;
  final String? title;

  const KomaChapterInfo({required this.id, this.title});

  @override
  int get hashCode => id.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KomaChapterInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title;
}
