// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lookup_one`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Look up metadata for many books. Open Library is primary; Google Books is
/// used when OL misses or returns an empty author+cover+genres set.
Future<List<BookMetadataResult>> lookupBooks({
  required List<BookLookupQuery> queries,
  String? googleApiKey,
}) => RustLib.instance.api.crateApiMetadataLookupBooks(
  queries: queries,
  googleApiKey: googleApiKey,
);

/// One book to look up. [id] is the Isar book id and is echoed in the result.
class BookLookupQuery {
  final PlatformInt64 id;
  final String title;
  final String? author;

  const BookLookupQuery({required this.id, required this.title, this.author});

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ author.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookLookupQuery &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          author == other.author;
}

/// Structured metadata for a single book, keyed by the input [id].
class BookMetadataResult {
  final PlatformInt64 id;
  final String title;
  final String? author;
  final String? coverUrl;
  final List<String> genres;
  final String? releaseDate;

  /// `"open_library"` or `"google_books"` when found; empty when not.
  final String source;
  final String? remoteId;
  final bool found;
  final String? error;

  const BookMetadataResult({
    required this.id,
    required this.title,
    this.author,
    this.coverUrl,
    required this.genres,
    this.releaseDate,
    required this.source,
    this.remoteId,
    required this.found,
    this.error,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      author.hashCode ^
      coverUrl.hashCode ^
      genres.hashCode ^
      releaseDate.hashCode ^
      source.hashCode ^
      remoteId.hashCode ^
      found.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookMetadataResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          author == other.author &&
          coverUrl == other.coverUrl &&
          genres == other.genres &&
          releaseDate == other.releaseDate &&
          source == other.source &&
          remoteId == other.remoteId &&
          found == other.found &&
          error == other.error;
}
